import { Request, Response } from 'express'

export function getNotifications(request: Request, response: Response) {
    // TODO : get all notifications in notifications models
    response.send([
        {
            id: 1,
            image: 'images/publlications/herydj.jpg',
            date: '5 min ago',
            personName: 'Hery dj',
            title: 'aooonna',
            type: 'publication',
            isSeen: false,
            idPublication: 1,
        },
        {
            id: 2,
            image: 'images/publlications/herydj.jpg',
            date: '5 min ago',
            personName: 'Hery dj',
            title: 'aooonna',
            type: 'publication',
            isSeen: false,
            idPublication: 1,
        },
        {
            id: 3,
            image: 'images/publlications/herydj.jpg',
            date: '5 min ago',
            personName: 'Hery dj',
            title: 'aooonna',
            type: 'publication',
            isSeen: true,
            idPublication: 2,
        },
        {
            id: 4,
            image: 'images/publlications/herydj.jpg',
            date: '5 min ago',
            personName: 'Hery dj',
            title: 'aooonna',
            type: 'publication',
            isSeen: true,
            idPublication: 2,
        },
        {
            id: 5,
            image: 'images/publlications/herydj.jpg',
            date: '5 min ago',
            personName: 'Hery dj',
            title: 'aooonna',
            type: 'publication',
            isSeen: false,
            idPublication: 1,
        },
        {
            id: 6,
            image: 'images/publlications/herydj.jpg',
            date: '5 min ago',
            personName: 'Hery dj',
            title: 'aooonna',
            type: 'publication',
            isSeen: false,
            idPublication: 1,
        },
        {
            id: 7,
            image: 'images/publlications/herydj.jpg',
            date: '5 min ago',
            personName: 'Hery dj',
            title: 'aooonna',
            type: 'publication',
            isSeen: true,
            idPublication: 2,
        },
        {
            id: 8,
            image: 'images/publlications/herydj.jpg',
            date: '5 min ago',
            personName: 'Hery dj',
            title: 'aooonna',
            type: 'publication',
            isSeen: true,
            idPublication: 2,
        },
    ])
}
